tunnel: 78d63aa1-8135-438b-ba09-8bad2c4e46ba
credentials-file: /home/benfreed/.cloudflared/78d63aa1-8135-438b-ba09-8bad2c4e46ba.json

ingress:
  - hostname: webhook-worker.codingincabins.xyz
    service: http://localhost:8788
  - service: http_status:404 