name = "webhook-worker"
main = "src/index.ts"
compatibility_date = "2024-01-05"

# Custom Domain configuration
routes = [
  { pattern = "webhook-worker.codingincabins.xyz", custom_domain = true }
]

[vars]
# Clerk
CLERK_WEBHOOK_SECRET = "whsec_ou/pM27flfuteyf/gL1GPYreMvBwMiF/"

# API configuration
API_URL = "http://localhost:8787"  # Local API server
API_SECRET = "test-api-secret"

[dev]
port = 8788
inspector_port = 9230 