name = "webhook-worker"
main = "src/index.ts"
compatibility_date = "2024-01-05"

# Custom Domain configuration
routes = [
  { pattern = "webhook-worker.codingincabins.xyz", custom_domain = true }
]

[vars]
# API configuration
API_URL = "http://localhost:8787"  # Local API server

[dev]
port = 8788
inspector_port = 9230
ip = "localhost"  # Use localhost 