# Wrangler configuration
name = "admin-cloudflare-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Development environment configuration
[env.development]
# Define vars that should be set but values will come from .dev.vars
vars = { ENVIRONMENT = "development" }

# Development server configuration
[dev]
port = 8787  # API port
ip = "localhost"  # Use localhost
local_protocol = "http"
inspector_port = 9232  # Different debug port for API
