# Wrangler configuration
name = "admin-cloudflare-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.development]
name = "admin-cloudflare-api-dev"
compatibility_date = "2024-01-01"

# Development server configuration
[dev]
port = 8787  # API port
ip = "localhost"
local_protocol = "http"
inspector_port = 9231  # Different debug port for API

# Environment variables
[env.development.vars]
ENVIRONMENT = "development"

# Production environment
[env.production]
name = "admin-cloudflare-api-prod"
vars = { ENVIRONMENT = "production" }

# Environment variables
[vars]
ENVIRONMENT = "development"
